version: "3"

services:
  master:
    build: .
    container_name: "master"
    ports:
      - "8089:8089"
    command: "--host=http://APPNODE-ELB-1396254919.us-east-2.elb.amazonaws.com --master"
  slave:
    build: .
    command: "--host=http://APPNODE-ELB-1396254919.us-east-2.elb.amazonaws.com --slave --master-host=master"
